//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estoque
    {
        public int Id { get; set; }
        public int Quantidade { get; set; }
        public decimal ValorUnitario { get; set; }
        public decimal ValorTotal { get; set; }
        public System.DateTime Data { get; set; }
        public int ProdutoId { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
