//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoVenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoVenda()
        {
            this.Itens = new HashSet<PedidoVendaItem>();
        }
    
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public decimal ValorSubTotal { get; set; }
        public decimal ValorImposto { get; set; }
        public decimal ValorTotal { get; set; }
        public System.DateTime DataInclusao { get; set; }
        public System.DateTime DataAlteracao { get; set; }
        public string UsuarioIdCaixa { get; set; }
        public int ClienteId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoVendaItem> Itens { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
